# arq_db_cp = 'DATA_BASE/SICRO_GO_10_2020_analitico_composicao_dado_basico.txt'
# arq_db_in = 'DATA_BASE/SICRO_GO_10_2020_sintetico_dado_basico.txt'
# arq_apr_in = 'DATA_BASE/SICRO_GO_10_2020_analitico_composicao_apropriacao.txt'
# arq_cto_in = 'DATA_BASE/SICRO_GO_10_2020_sintetico_custo_unitario.txt'

# arq_db_cp = 'DATA_BASE/SICRO_GO_04_2023_analitico_composicao_dado_basico_V1.txt'
# arq_db_in = 'DATA_BASE/SICRO_GO_04_2023_sintetico_dado_basico_V1.txt'
# arq_apr_in = 'DATA_BASE/SICRO_GO_04_2023_analitico_composicao_apropriacao_V1.txt'
# arq_cto_in = 'DATA_BASE/SICRO_GO_04_2023_sintetico_custo_unitario_V1.txt'
# arq_db_al_an = 'REPOSITORIO/SICRO_ZZ_00_0000_analitico_outros_dado_basico.txt'
# arq_apr_al = 'REPOSITORIO/SICRO_ZZ_00_0000_analitico_outros_apropriacao.txt'
# arq_db_al_st = 'REPOSITORIO/SICRO_ZZ_00_0000_sintetico_outros_dado_basico.txt'
# arq_dmt = 'REPOSITORIO/dmt_material.txt'

arq_apr_in = 'DATA_BASE/SICRO_GO_01_2024_analitico_composicao_apropriacao.txt'
arq_db_cp = 'DATA_BASE/SICRO_GO_01_2024_analitico_composicao_dado_basico.txt'
arq_cto_in = 'DATA_BASE/SICRO_GO_01_2024_sintetico_custo_unitario.txt'
arq_db_in = 'DATA_BASE/SICRO_GO_01_2024_sintetico_dado_basico.txt'

arq_db_al_an = 'REPOSITORIO/SICRO_ZZ_00_0000_analitico_outros_dado_basico.txt'
arq_apr_al = 'REPOSITORIO/SICRO_ZZ_00_0000_analitico_outros_apropriacao.txt'
arq_db_al_st = 'REPOSITORIO/SICRO_ZZ_00_0000_sintetico_outros_dado_basico.txt'
arq_dmt = 'REPOSITORIO/dmt_material.txt'